### ISSUE TITLE
Documentation unacessible

### ISSUE THREAD

**Issue by johncwok** [JuliaDocs/Documenter.jl#1421]
I hope this is not a dumb question: I created a package with ```PkgTemplate``` which makes use of ```documenter```. I want to write a documentation for it. When I run ```make.jl```, the output is excactly like in the doc of ```Documenter``` so everything seems to works nicely but when I try to go on the link of my doc https://johncwok.github.io/CategoricalTimeSeries.jl/stable I just get an error 404, I tried various things but nothing worked and I am puzzled. 
Can someone help me ? This is the first time I make a doc so I have no idea where to start, also I have never made a website before.

**Comment by mortenpi** [comment]
It looks like building documentation on CI is failing: https://github.com/johncwok/CategoricalTimeSeries.jl/runs/1151530216?check_suite_focus=true

I think fixing the dependencies of the package (i.e. adding Reexport as a dep) should fix it?

**Comment by johncwok** [comment]
This will be hard to fix, looking at the log, I get the following error:

```Julia
ERROR: Unsatisfiable requirements detected for package IntegerIB [6503ae40]:
 IntegerIB [6503ae40] log:
 ├─possible versions are: 0.1.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left```
I have google a bit, this is an obscure message than can have several causes, there are some workarounds when working locally but so far I have not found any solution for this issue when it appears on a CI build.

I think i'll give up on Julia for this one and use some more robust utility to build the docs.

**Comment by fredrikekre** [comment]
> restricted by julia compatibility requirements to versions: uninstalled — no versions left

this means that the package does not support the running version of Julia. If you look at the package registry you see that, indeed, this package requires Julia >= 1.2:
```
$ cat ~/.julia/registries/General/I/IntegerIB/Compat.toml 
[0]
DataFrames = "0.19.4-0.19"
julia = "1.2.0-1"
```
and you are running Julia 1.0 on CI.

**Comment by johncwok** [comment]
I changed the requirement to julia 1.0 but still get excactly the same error message.

**Comment by fredrikekre** [comment]
Please link to the logs. I still see https://github.com/johncwok/CategoricalTimeSeries.jl/blob/master/.github/workflows/ci.yml#L12-L14 for example.

**Comment by johncwok** [comment]
https://github.com/johncwok/CategoricalTimeSeries.jl/runs/1154477925

**Comment by fredrikekre** [comment]
Yes? But that is Julia 1.0, see https://github.com/JuliaDocs/Documenter.jl/issues/1421#issuecomment-697285770

**Comment by fredrikekre** [comment]
I told you already; https://github.com/JuliaDocs/Documenter.jl/issues/1421#issuecomment-697285770 You can not use Julia 1.0 or 1.1. Perhaps you should ask general CI questions on https://discourse.julialang.org/ instead.

Lets focus on the Documenter issue, which is: https://github.com/johncwok/CategoricalTimeSeries.jl/runs/1154477892?check_suite_focus=true#step:5:27 and suggest you either don't have a key, or you have uploaded a corrupt one.

**Comment by johncwok** [comment]
I don't really understand what you mean. You first told the CI is running on julia 1.0 so I cannot require 1.2, when I suppressed this requirement and it still doesn't work, you reply that I also cannot use julia 1.0 ? Anyways, I do not want to take up too much of your time so let's forget about this.
What do you mean by key ? I didn't create the doc myself I let the package do it for me.
Would it be faster to make the doc myself from scratch or to use the package ? Github indicates that one need to make an extra repository just for hosting the doc maybe I should do this.

**Comment by KristofferC** [comment]
>  You first told the CI is running on julia 1.0 so I cannot require 1.2, when I suppressed this requirement and it still doesn't work, you reply that I also cannot use julia 1.0 ?

The dependency `IntegerIB` requires Julia 1.2+. Since you use that as a dependency, the package can also only be installed on Julia 1.2+. So run your documentation generation on Julia 1.2+.

**Comment by johncwok** [comment]
I changed that (#issuecomment-697510294), I got rid of this requirement, yet the build still fails.

**Comment by KristofferC** [comment]
> I changed that (#issuecomment-697510294), I got rid of this requirement, yet the build still fails.

You need to register a new version of the package with the requirement then. In the registry (https://github.com/JuliaRegistries/General/blob/master/I/IntegerIB/Compat.toml#L3) it is still 1.2.

**Comment by johncwok** [comment]
I give up, it's too time consuming. I'll use python to make the docs.
