### ISSUE TITLE
Search results: link directly to page rather than top-level section name (aka the page title)

### ISSUE THREAD

**Issue by waldyrious** [JuliaDocs/Documenter.jl#632]
Initially reported as part of #629. In the example there, a search for "markdown" (http://docs.julialang.org/en/latest/search/?q=markdown) produced the following entries among the results:

- https://docs.julialang.org/en/latest/stdlib/Markdown/#
- https://docs.julialang.org/en/latest/stdlib/Markdown/#Markdown-1
- https://docs.julialang.org/en/latest/manual/documentation/#Documentation-1

The second link above is redundant with the first one, and the third should have been simply https://docs.julialang.org/en/latest/manual/documentation/# (I'd remove the `#` as well, but that's a minor issue).

**Comment by odow** [comment]
Closing because this seems to have been fixed. I can't reproduce with https://docs.julialang.org/en/v1/search/?q=Markdown.

**Comment by waldyrious** [comment]
> The second link above is redundant with the first one

This still happens with the updated link you provided.

**Comment by odow** [comment]
Perhaps I misunderstand then. Why exactly is that a problem?

**Comment by mortenpi** [comment]
FWIW, I think the same sections are still present with the new front-end / minisearch as well:

![image](https://github.com/JuliaDocs/Documenter.jl/assets/147757/b601dacb-8a99-4d84-b1cc-07720e5f7ba5)

**Comment by odow** [comment]
I don't really understand the problem though. One is a page name, one is a section header?

**Comment by mortenpi** [comment]
I think the fundamental problem here is that we have both pages, and each heading individually as part of the index separately. So the search engine has no idea that those are kinda the same thing.

cc @Hetarth02 just as an FYI, if you happen to have any thoughts.

**Comment by Hetarth02** [comment]
Yeah, we could do a url parse and add something like an accordian to group up the same urls under one.

For example,

test.com/markdown
   - test.com/markdown#123
   - test.com/markdown#456

**Comment by mortenpi** [comment]
I don't think we need a UI solution this. We just shouldn't show the results, either by removing them from the JSON index, or ignoring on the minisearch level somehow.

**Comment by Hetarth02** [comment]
As I said earlier, we could group results under same page and make an accordian/dropdown with a visual hint. Will work on some mockups for the same(might take a little bit). Open to other ideas as well.

**Comment by waldyrious** [comment]
> I don't really understand the problem though. One is a page name, one is a section header?

In my previous comments I described having both the page title and the **top-level** section as independent entries in the search as being "redundant", but @mortenpi put it more clearly: those are essentially the same thing, and thus duplicates. The reason this is bad is that each additional entry in a search results listing introduces additional noise and makes it harder to locate the actual content one may be looking for (even if it the content being search for is one of those, because it forces the reader to understand that they both refer to the same thing).

I also agree with him that the solution shouldn't be folding the extra results (which I see as "sweeping the dirt under the rug", if you'll pardon the expression). The correct solution is indeed, as @mortenpi said, to not include the redundant entries in the search results in the first place.
